spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/
          username:
          password:
          basedir: /Users/GitConfigBase
  rabbitmq:
    host: 192.168.1.233
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"