spring:
  application:
    name: task
  datasource:
    url: jdbc:postgresql://192.168.1.233/taskdb
    username: postgres
    password: password
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
